services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password!23
    ports:
      - "1433:1433"
    networks:
      - keycloak-network

  mssql-scripts:
    depends_on:
      - mssql
    image: mcr.microsoft.com/mssql-tools
    networks:
      - keycloak-network
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "Password!23" -Q "create database Keycloak"; do sleep 10; done'

  keycloak:
    depends_on:
      - mssql-scripts
    image: jboss/keycloak:12.0.3
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mssql
      - DB_USER=sa
      - DB_PASSWORD=Password!23
      - DB_ADDR=mssql 
      - DB_DATABASE=Keycloak 
    networks:
      - keycloak-network

networks:
  keycloak-network: {}



   